# Generated by Django 4.1.4 on 2022-12-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='Places/'),
        ),
        migrations.AlterField(
            model_name='proberty_book',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Property', to='property.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property_category', to='property.category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property_place', to='property.place'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property_image', to='property.property'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='Propertyimages/'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_Property', to='property.property'),
        ),
    ]
