# Generated by Django 4.1.4 on 2022-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_place_image_alter_proberty_book_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proberty_book',
            name='children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='proberty_book',
            name='guest',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
